### ISSUE TITLE
Consider to add _bytes suffix to the metric name

### ISSUE THREAD

**Issue by 7840vz** [mrlhansen/idrac_exporter#10]
Thanks for our exporter again.
Just some more metric change to consider:

To help understand what is returned by idrac_memory_size metric, convert the value returned to base unit (bytes) and add `_bytes` suffix to the metric name. 

`idrac_memory_size_bytes` and 
This suffix can help to understand what units should be used with memory. 

Or at least add _mebibytes suffix.

```
...should have a suffix describing the unit, in plural form. Note that an accumulating count has total as a suffix, in addition to the unit if applicable.
http_request_duration_seconds
node_memory_usage_bytes
```

```
Prometheus does not have any units hard coded. For better compatibility, base units should be used. 
```

https://prometheus.io/docs/practices/naming/#base-units

**Comment by mrlhansen** [comment]
Thanks, I am happy to see many people actually using the exporter :)

I agree it's a bit arbitrary to report the size in MiB, so I adjusted the name. I have renamed several metrics lately, hopefully the names can become reasonably stable now.

**Comment by 7840vz** [comment]
thanks!!
