### ISSUE TITLE
Rename project to better fit its purpose.

### ISSUE THREAD

**Issue by ArKam** [mrlhansen/idrac_exporter#100]
As this project aim to export metrics from the server BMC Redfish API, wouldn't it be clearer to call it redfish_exporter rather than idrac_exporter?

idrac/ilo metrics can be pulled from multiple interfaces like IPMI/SNMP/REDFISH, this exporter focusing on the redfish implementation, that would make more sense to name it properly isn't?

Nonetheless, thanks for the hard work!

**Comment by mrlhansen** [comment]
Hi @ArKam 

Yes, this has been mentioned a few times - and in principle I agree, the name is no longer optimal. However, renaming it now that is has quite a few users poses some complications (or annoyances). 

* There are already several exporters called "redfish exporter" so I am not sure that is a great name either.
* I would need to create a new docker repository, while still keeping the old one around to not break existing installations.
* Renaming the repository would break all Helm installations, they would need to add a new repository.

Essentially I would need to archive the current repository and create a new one, to not break installations for current users.
