### ISSUE TITLE
Can /metrics endpoint be served over TLS?

### ISSUE THREAD

**Issue by elvinup** [mrlhansen/idrac_exporter#104]
Sweet exporter you have here :)

Just wondering if it would be possible to support TLS as that's usually what's required of our org for exporter endpoints.

Am guessing something similar [to this](https://github.com/MauveSoftware/ilo_exporter/blob/3283bf7de1339a31ceeb77d2ceecb8dd44747964/main.go#L100C21-L100C38) would work since this is also written in Go?

**Comment by mrlhansen** [comment]
Thank you!

I pushed a new commit that enables TLS support for the exporter. I will make a new release soon with the changes.

**Comment by mrlhansen** [comment]
New release is out. Let me know if you encounter any problems.
