### ISSUE TITLE
PSU - Not all appearing

### ISSUE THREAD

**Issue by lesphinks** [mrlhansen/idrac_exporter#105]
Hi,

All PSU readings under the `idrac_power_supply_***` commands are not working properly when you have mutliple PSUs.
They only show 2 PSU at maximum and I have systems with up to 6x PSU.

Also, the health reading does not show failed PSU:
`idrac_power_supply_health`

Seems to filter the failed or warning PSU.

ps: thank you for this great tool, it's really nice !!! 
I'm currently deploying a big cluster and testing it.
Let me know if you want me to test anything in particular.

**Comment by mrlhansen** [comment]
Hi @lesphinks 

If the PSUs are not being reported, then they are not being reported as being enabled by Redfish. I also have machines with up to 6 PSUs and they are all being reported. Information is sometimes lacking and inconsistent, so let's see what we can do in your case.

* What type of machine is it? (Vendor and Model)
* Can you run the program with the `-verbose` flag and attach the output when scraping the target that is not working correctly? I will need a dump of the JSON output to debug it and the `-verbose` flag will tell us which paths are needed.

**Comment by antux18** [comment]
Hello,

I have the same issue with Dell PowerEdge R640 machines that have two power supplies, with one being unplugged.

The Redfish request shows both power supplies, but for the unplugged one, the "Status" field is as follows:
```
"Status": {
    "Health": "Critical",
    "State": "UnavailableOffline"
},
```
Whereas the plugged one has the following status:
```
"Status": {
    "Health": "OK",
    "State": "Enabled"
},
```

The first one is indeed not reported as "Enabled" by Redfish, but I'd still like it to be listed by the exporter. Removing the condition at client.go:621 seems to fix the issue.

**Comment by mrlhansen** [comment]
Hi @antux18. I will change the condition, such that unless the state is explicitly reported as `Absent` then it will be included.
