### ISSUE TITLE
can you separate out the manufacturer name/hard disk/CPU and other information as a separate metric?

### ISSUE THREAD

**Issue by ilanni2460** [mrlhansen/idrac_exporter#107]
Sir, can you separate out the manufacturer name/hard disk/CPU/SKU and other information as a separate metric?

I want to display these separately on grafana as a metric.

![1](https://github.com/user-attachments/assets/da723274-b92b-4ee7-9571-fc52a98865bb)

**Comment by mrlhansen** [comment]
I am sure fully understand the issue, but there is no reason for splitting these labels across multiple metrics. Grafana has all the tools for using (and reusing) labels from the same metric. I believe this is just a matter of configuring the dashboard correctly in Grafana.

**Comment by ilanni2460** [comment]
@mrlhansen 
Sorry, I didn't describe it clearly. The metrics idrac_system_machine_info has many labels. I want it to be displayed in the grafana table, but I don't know how to configure it.

`
idrac_system_machine_info{app="数据采集", app_address="192.167.79.13", app_name="TEST1", company="TEST", instance="192.168.0.121", ip_address="192.168.0.121", job="sanhua_idrac_host", manufacturer="Dell Inc.", model="PowerEdge R730", name="数据采集", serial="C4G0239", server_type="物理机", sku="JXV6B
23X2"}

`

**Comment by ilanni2460** [comment]
@mrlhansen I have solved this problem. I need to use the label plug-in.
