### ISSUE TITLE
How to configure idrc_exporter proxy to capture remote host information

### ISSUE THREAD

**Issue by ilanni2460** [mrlhansen/idrac_exporter#108]
How to configure idrc_exporter proxy to capture remote host information

**Comment by mrlhansen** [comment]
What do you mean by "remote host information"? An example of the configuration for Prometheus is shown in the README file.

**Comment by ilanni2460** [comment]
@mrlhansen 
"remote host information"
It means that Dell's iradc host cannot be directly accessed by Idrac_exporter, and needs to be accessed by idrac_exporter through a proxy.

**Comment by mrlhansen** [comment]
If you mean support for a normal http proxy, then that should be doable. I can try to look into it.

**Comment by mrlhansen** [comment]
I pushed a one line change that should enable support for http proxies. If you simply define the environment variable `https_proxy` the exporter should now pick this up and use the proxy automatically.

**Comment by ilanni2460** [comment]
> I pushed a one line change that should enable support for http proxies. If you simply define the environment variable `https_proxy` the exporter should now pick this up and use the proxy automatically.

Thank you very much for your reply. I have the http_proxy variable in the configuration file of Idrac_exporter. How should I use it?

**Comment by mrlhansen** [comment]
Just to be clear, you need to compile the code yourself to test it.

The `https_proxy` is an environment variable, so you should set this before running the program, something like this:

```sh
export https_proxy="http://myproxy:8000" # replace with your actual proxy
./idrac_exporter -config config.yml
```

**Comment by ilanni2460** [comment]
@mrlhansen 

Is it possible to add it in the configuration file of idrac_exporter

**Comment by mrlhansen** [comment]
In principle yes, but I like the idea of this being set as part of the environment instead. Is there a specific need to have this in the configuration file?

**Comment by ilanni2460** [comment]
> In principle yes, but I like the idea of this being set as part of the environment instead. Is there a specific need to have this in the configuration file?

I don’t recommend writing it in environment variables, because there are other applications that don’t need to use a proxy.

**Comment by mrlhansen** [comment]
Okay, I think there is an easy way to implement support for both scenarios. I will try to do it in the next few days.

**Comment by ilanni2460** [comment]
@mrlhansen I am really looking forward to it.

**Comment by mrlhansen** [comment]
It's now possible to use `https_proxy` in the configuration file. I will make a new release soon.
