### ISSUE TITLE
Timeout between requests

### ISSUE THREAD

**Issue by MrWeez** [mrlhansen/idrac_exporter#109]
Is it possible to set the time interval after which the request will be made? My iDRAC web interface takes a long time to load, so the exporter cannot always wait for a response, which sometimes causes statistics to miss on the Grafana side

**Comment by MrWeez** [comment]
It also sometimes outputs null values, which is why the grafana graph is so uneven.

**Comment by mrlhansen** [comment]
Hi @MrWeez 

There are two timeouts you can adjust, one in the idrac_exporter and one in Prometheus.

In the configuration file for the idrac_exporter you have the `timeout` variable, which is the timeout for each call to iDRAC/Redfish. Usually 10s is enough here, but you can increase it if needed (you will see errors in the log if timeouts happen).

In the configuration file for prometheus you have the `scrape_timeout` variable. Depending on how many metrics you are collecting, this might need to be increased to 60s or maybe even 90s, depending on the machines.

Finally, if iDRAC is really slow, try restarting iDRAC itself, it usually helps for me.

**Comment by MrWeez** [comment]
> scrape_timeout

Thank you very much, I was able to solve the problem by playing with the frequency of collecting metrics and timeouts
