### ISSUE TITLE
HardDrives on HPE systems can have the same IDs causing a whole metrics collecting to fail for the server

### ISSUE THREAD

**Issue by AlexG14** [mrlhansen/idrac_exporter#110]
Hi.

ProLiant DL380e Gen8 + D7300 Disk Enclosure.
Raw Output for 2 disc controllers:
[redfish_output.txt](https://github.com/user-attachments/files/18145552/redfish_output.txt)

Using only the disk number as ID causing a failure:

2024-12-16T04:03:42.201 ERROR Error collecting metrics for host <ServerName is redacted>: 12 error(s) occurred:
* collected metric "hardware_drive_health" { label:{name:"id"  value:"16"}  label:{name:"status"  value:"OK"}  gauge:{value:0}} was collected before with the same name and label values
* collected metric "hardware_drive_capacity_bytes" { label:{name:"id"  value:"16"}  gauge:{value:9.00184670208e+11}} was collected before with the same name and label values
* collected metric "hardware_drive_life_left_percent" { label:{name:"id"  value:"16"}  gauge:{value:100}} was collected before with the same name and label values
* collected metric "hardware_drive_health" { label:{name:"id"  value:"17"}  label:{name:"status"  value:"OK"}  gauge:{value:0}} was collected before with the same name and label values
* collected metric "hardware_drive_capacity_bytes" { label:{name:"id"  value:"17"}  gauge:{value:9.00184670208e+11}} was collected before with the same name and label values
* collected metric "hardware_drive_life_left_percent" { label:{name:"id"  value:"17"}  gauge:{value:100}} was collected before with the same name and label values
* collected metric "hardware_drive_health" { label:{name:"id"  value:"18"}  label:{name:"status"  value:"OK"}  gauge:{value:0}} was collected before with the same name and label values
* collected metric "hardware_drive_capacity_bytes" { label:{name:"id"  value:"18"}  gauge:{value:9.00184670208e+11}} was collected before with the same name and label values
* collected metric "hardware_drive_life_left_percent" { label:{name:"id"  value:"18"}  gauge:{value:100}} was collected before with the same name and label values
* collected metric "hardware_drive_health" { label:{name:"id"  value:"19"}  label:{name:"status"  value:"OK"}  gauge:{value:0}} was collected before with the same name and label values
* collected metric "hardware_drive_capacity_bytes" { label:{name:"id"  value:"19"}  gauge:{value:9.00184670208e+11}} was collected before with the same name and label values
* collected metric "hardware_drive_life_left_percent" { label:{name:"id"  value:"19"}  gauge:{value:100}} was collected before with the same name and label values

I think it would be better to use something like a pair "controller ID_Disk ID" as id for disk drives. 
Thank you!

**Comment by mrlhansen** [comment]
Hi @AlexG14 

Thank you for the Redfish output. I will have a look. From what I can see, I will probably just add another label with a controller ID to all the metrics.
