### ISSUE TITLE
Questions about the SN serial number of HPE/New H3C/Inspur servers

### ISSUE THREAD

**Issue by ilanni2460** [mrlhansen/idrac_exporter#111]
Questions about the SN serial number of HPE/New H3C/Inspur servers

For Dell servers, sku is used to represent the SN serial number, while for servers such as HPE/New H3C/Inspur, serial is used to represent the SN serial number.

for Inspur Server，no sku label:

idrac_system_machine_info{app="muju", app_address="192.69.91.21", app_name="muju", instance="192.170.70.112", ip_address="192.69.4.106", job="sanhua_idrac_host", manufacturer="Inspur", model="NF7050M6", name="moju", serial="27B601671"}
![Inspur](https://github.com/user-attachments/assets/c8e679e9-7843-4bee-8981-d1360635921f)

for HPE Server，no sku label:

idrac_system_machine_info{app="PES", app_address="192.69.91.15", app_name="PES", instance="192.170.70.113", ip_address="192.69.4.107", job="sanhua_idrac_host", manufacturer="New H3C Technologies Co., Ltd.", model="H3C UniServer R4900 G5", name="PES", serial="21020697"}
![hpe](https://github.com/user-attachments/assets/fd506ce5-c940-4a69-9493-8dc076e8d98b)

for New H3C Server:

idrac_system_machine_info{app="PLM", app_address="192.69.91.16", app_name="PLM", instance="192.170.70.113", ip_address="192.69.4.108", job="sanhua_idrac_host", manufacturer="HPE", model="ProLiant DL580 Gen9", name="PLM", serial="CN70JJM", sku="8160-AA1"}
![h3c](https://github.com/user-attachments/assets/64b4bbe4-5b60-4667-a4d0-dd0d225019b8)

**Is it possible to unify the SN serial numbers of these models of servers into SKUs?**

**Comment by mrlhansen** [comment]
This is not something I will change in the exporter. However, you can do this with a query in Prometheus. For example, if you want to use `sku` as `serial` for Dell servers, you can use something like this:

```
label_replace(idrac_system_machine_info{manufacturer=~"Dell.*"}, "serial", "$1", "sku", "(.+)") or on(instance) idrac_system_machine_info
```

This should result in a list of metrics, where "serial" has the value you want in all cases.

**Comment by ilanni2460** [comment]
> This is not something I will change in the exporter. However, you can do this with a query in Prometheus. For example, if you want to use `sku` as `serial` for Dell servers, you can use something like this:
> 
> ```
> label_replace(idrac_system_machine_info{manufacturer=~"Dell.*"}, "serial", "$1", "sku", "(.+)") or on(instance) idrac_system_machine_info
> ```
> 
> This should result in a list of metrics, where "serial" has the value you want in all cases.

Thank you very much for your prompt reply. I have modified the label value according to your suggestion.

![1](https://github.com/user-attachments/assets/1d0b2993-7299-4634-b633-dcb2b8bfa46f)
