### ISSUE TITLE
[iDRAC 8] json: cannot unmarshal array into Go struct field .Members.EntryCode of type string

### ISSUE THREAD

**Issue by jaredhendrickson13** [mrlhansen/idrac_exporter#14]
Hi!

First off, thanks for your work on this! We have a mix of iDRAC 8 and iDRAC 9 enabled systems that I'd love to get monitored using this.  I am able to use this with iDRAC 9 no problem, but with iDRAC 8 I intermittently get the following error: 

```
2023-02-02T18:25:19.480 DEBUG Error decoding response from url "https://x.x.x.x/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel": json: cannot unmarshal array into Go struct field .Members.EntryCode of type string
```

This is an example API response I get directly from from `redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel` on iDRAC 8:
```json
{
  "@odata.context": "/redfish/v1/$metadata#LogEntryCollection.LogEntryCollection",
  "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel",
  "@odata.type": "#LogEntryCollection.LogEntryCollection",
  "Description": "System Event Logs for this manager",
  "Members": [
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/1",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2021-03-05T23:10:36-06:00",
      "Description": " Log Entry 1",
      "EntryCode": [
        {
          "Member": "Assert"
        }
      ],
      "EntryType": "SEL",
      "Id": "1",
      "Links": {},
      "Message": "The CMOS battery has failed.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "1ffff",
      "Name": " Log Entry 1",
      "SensorNumber": 101,
      "SensorType": [
        {
          "Member": "Battery"
        }
      ],
      "Severity": "Critical"
    }
  ],
  "Members@odata.count": 1,
  "Members@odata.nextLink": "",
  "Name": "Log Entry Collection"
}
```

`EntryCode` is an array of objects on iDRAC 8 but is a string on iDRAC 9. Is this something that can be addressed?

Thanks again!

**Comment by mrlhansen** [comment]
Hi,

Thanks for reporting this. I will have a look as soon as possible. It should not be difficult to fix :)

**Comment by mrlhansen** [comment]
I pushed a minor change. Can you check if it works?

**Comment by jaredhendrickson13** [comment]
Yes, that seems to have fixed that specific error! But I'm now getting another regarding the `SensorType`. Looks like the same situation for that field:
```
2023-02-03T16:14:54.491 ERROR Error collecting metrics for host x.x.x.x: json: cannot unmarshal array into Go struct field .Members.SensorType of type string
````

I'm also now noticing errors from `/redfish/v1/Chassis/System.Embedded.1/Thermal`. I probably just missed these originally and they aren't related to your change, but it also looks like a similar type situation:

```
2023-02-03T16:15:38.428 ERROR Error collecting metrics for host x.x.x.x: json: cannot unmarshal array into Go struct field .Redundancy.Mode of type string
```

Where `Redundancy` looks like this on iDRAC 8 with `Mode` also being an array of objects instead of a string:
```json
"Redundancy": [
    {
      "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Thermal/Redundancy/iDRAC.Embedded.1%23SystemBoardFanRedundancy",
      "MaxNumSupported": null,
      "MemberId": "iDRAC.Embedded.1#SystemBoardFanRedundancy",
      "MinNumNeeded": null,
      "Mode": [
        {
          "Member": "FailOver"
        }
      ],
      "Name": "System Board Fan Redundancy",
      "RedundancySet": [],
      "RedundancySet@odata.count": 0,
      "Status": {
        "Health": "OK",
        "State": "Enabled"
      }
    }
  ]
```

I appreciate the help!

**Comment by mrlhansen** [comment]
I made some more change to the code. It should work now, but I will probably try to implement a more elegant solution later on, to handle these cases more consistently.

Unfortunately I do not have any iDRAC 8 to test on, so am happy you can help testing it!

**Comment by jaredhendrickson13** [comment]
Looks like it is working now. Thanks! Much appreciated.
