### ISSUE TITLE
Can't connect to 9348

### ISSUE THREAD

**Issue by chosey85** [mrlhansen/idrac_exporter#15]
Hi,

I've created a local file called idrac.yml.
I've set the bind address to 127.0.0.1 and port to 9348.
I've added to the docker file COPY idrac.yml /etc/prometheus/idrac.yml.
The I've built the docker image.
I call it as follows: docker run -p 9348:9348 -d idrac_exporter.

When I run docker logs idrac_exporter I get "INFO  Server listening on 127.0.0.1:9348"

The issue is that when I try to connect to my server from another server in the network to http://servername:9348, I get an "unable to connect error". 

Am I doing something wrong?

**Comment by mrlhansen** [comment]
Hi,

Try setting the bind address to `0.0.0.0` then I believe it should work properly. If you only listen to the localhost interface (127.0.0.1) inside the container, then port forwarding to the host does not work.
