### ISSUE TITLE
Power Reading

### ISSUE THREAD

**Issue by miroslavmasaryk3221** [mrlhansen/idrac_exporter#2]
Hello @dstndstn @mrlhansen 

Would it be possible to add power reading? 

Thanks

**Comment by mrlhansen** [comment]
I haven't checked, but it should defintely be possible. I can try to have a look when I find a little time.

**Comment by mrlhansen** [comment]
I had a look at what data is available from the API and these are the kind of metrics I can pull.
```
idrac_power_output_watts{psu="0"} 74.5
idrac_power_input_watts{psu="0"} 89
idrac_power_capacity_watts{psu="0"} 750
idrac_power_input_voltage{psu="0"} 232
idrac_power_efficiency_percent{psu="0"} 91

idrac_power_output_watts{psu="1"} 67
idrac_power_input_watts{psu="1"} 77.62
idrac_power_capacity_watts{psu="1"} 750
idrac_power_input_voltage{psu="1"} 232
idrac_power_efficiency_percent{psu="1"} 91
```

Depending a bit on the iDRAC version, some of these metrics might simply be reported as zero it seems.

Is this what you are looking for @miroslavmasaryk3221 ? I haven't pushed the new code yet.

**Comment by miroslavmasaryk3221** [comment]
Yes, Please push the new code, I will test it on HP ILO.

Thanks

**Comment by mrlhansen** [comment]
I pushed the new code, let me know if there are any problems. There is a new "power" flag in the configuration file to select the power metrics. Have a look at the updated README file.

**Comment by miroslavmasaryk3221** [comment]
Thanks, I will check that ;)
