### ISSUE TITLE
bios metric to include server model 

### ISSUE THREAD

**Issue by miked314** [mrlhansen/idrac_exporter#20]
I think it would be very useful to include server model with bios metric. this would allow to easily create firmware fragmentations lists.

**Comment by mrlhansen** [comment]
Hi @miked314

The server model is already reported in the `idrac_machine_info` metric. If you want to get both, I suggest to make a Promtheus query that combines information from the two. This could be something like:

```
idrac_bios_info * on(instance) group_left(model) idrac_machine_info
```

In my case this would return entries like this:
```
{instance="192.168.10.10", job="idrac", model="PowerEdge R640", version="2.14.2"}
```
