### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by 9206284** [mrlhansen/idrac_exporter#21]
I built an image file using a Git project and ran it. When I tried to manually trigger 'curl http://192.168.229.228:9348/metrics?target=192.168.229.36', it returned the error message 'curl: (52) Empty reply from server'. When I checked the container logs, I found the following error:

2023-05-05T06:04:38.551 INFO Server listening on 0.0.0.0:9348
2023/05/05 06:05:25 http: panic serving 192.168.229.228:50906: runtime error: invalid memory address or nil pointer dereference
goroutine 37 [running]:
net/http.(*conn).serve.func1()
/usr/local/go/src/net/http/server.go:1850 +0xbf
panic({0x6e8bc0, 0x971420})
/usr/local/go/src/runtime/panic.go:890 +0x262
github.com/mrlhansen/idrac_exporter/internal/redfish.(*Client).RefreshStorage(0xc000190150, {0x7bea40, 0xc00011c228})
/app/src/internal/redfish/client.go:272 +0x258
github.com/mrlhansen/idrac_exporter/internal/promexporter.(*metricsCollector).CollectMetrics(0xc0001138f0)
/app/src/internal/promexporter/collector.go:78 +0x1bf
github.com/mrlhansen/idrac_exporter/internal/promexporter.MetricsHandler({0x7c10e0, 0xc0001b80e0}, 0xc000194300)
/app/src/internal/promexporter/http.go:49 +0x312
net/http.HandlerFunc.ServeHTTP(0xc000042af0?, {0x7c10e0?, 0xc0001b80e0?}, 0x0?)
/usr/local/go/src/net/http/server.go:2109 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc0001342dd?, {0x7c10e0, 0xc0001b80e0}, 0xc000194300)
/usr/local/go/src/net/http/server.go:2487 +0x149
net/http.serverHandler.ServeHTTP({0xc0001137a0?}, {0x7c10e0, 0xc0001b80e0}, 0xc000194300)
/usr/local/go/src/net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc000124d20, {0x7c1540, 0xc0001134a0})
/usr/local/go/src/net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
/usr/local/go/src/net/http/server.go:3102 +0x4db

It seems like a programming issue.

**Comment by mrlhansen** [comment]
Hi Derrick,

Yes, it is a bug in the program. I will implement a fix. What machine model are you trying this on?

**Comment by 9206284** [comment]
Thank you very much, bug has been fixed. 👍

**Comment by hans-op** [comment]
This error will occur when running in the ipmi environment.
I accidentally entered the wrong ipmi address when I entered the idrac address and found this problem
