### ISSUE TITLE
Request for support of Dell hardware memory status in the project.

### ISSUE THREAD

**Issue by 9206284** [mrlhansen/idrac_exporter#22]
Hello,

I'm interested in using your project, and I noticed that it currently does not support monitoring the memory status of Dell hardware. I was wondering if it would be possible for you to add this feature to your project?

I appreciate your work on this project and any help or guidance you can provide.

Thank you.

**Comment by mrlhansen** [comment]
Hi @9206284 

I will have a look. If I remember correctly, then it should be quick to implement.

**Comment by mrlhansen** [comment]
I wrote some code to collect information for all DIMM modules. Below is an example of the exported metrics for each DIMM:

```
idrac_memory_module_info{ecc="MultiBitECC",id="DIMM.Socket.B5",manufacturer="Micron Technology",name="DIMM B5",rank="2",serial="31B4BB1F",type="DDR4"} 1
idrac_memory_module_health{id="DIMM.Socket.B5",state="OK"} 0
idrac_memory_module_capacity_bytes{id="DIMM.Socket.B5"} 34359738368
idrac_memory_module_speed_mhz{id="DIMM.Socket.B5"} 2400
```

Is this what you had in mind? Any suggestions?

**Comment by 9206284** [comment]
Thank&nbsp;you&nbsp;for&nbsp;providing&nbsp;the&nbsp;example&nbsp;content,&nbsp;it&nbsp;has&nbsp;exceeded&nbsp;my&nbsp;expectations.&nbsp;It's&nbsp;fantastic!
I&nbsp;truly&nbsp;appreciate&nbsp;your&nbsp;help&nbsp;and&nbsp;wish&nbsp;your&nbsp;project&nbsp;receives&nbsp;even&nbsp;more&nbsp;attention.&nbsp;


Paulie
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Martin ***@***.***&gt;; 
发送时间: 2023年5月15日(星期一) 晚上7:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mrlhansen/idrac_exporter] Request for support of Dell hardware memory status in the project. (Issue #22)





 
I wrote some code to collect information for all DIMM modules. Below is an example of the exported metrics for each DIMM:
 idrac_memory_module_info{ecc="MultiBitECC",id="DIMM.Socket.B5",manufacturer="Micron Technology",name="DIMM B5",rank="2",serial="31B4BB1F",type="DDR4"} 1 idrac_memory_module_health{id="DIMM.Socket.B5",state="OK"} 0 idrac_memory_module_capacity_bytes{id="DIMM.Socket.B5"} 34359738368 idrac_memory_module_speed_mhz{id="DIMM.Socket.B5"} 2400  
Is this what you had in mind? Any suggestions?

**Comment by mrlhansen** [comment]
Thank you very much!

I pushed the new code to the repository now :)
