### ISSUE TITLE
Can only scrape from localhost

### ISSUE THREAD

**Issue by trippinnik** [mrlhansen/idrac_exporter#28]
address: 0.0.0.0 # Listen address
port: 9348         # Listen port
timeout: 10        # HTTP timeout (in seconds) for Redfish API calls
retries: 1         # Number of retries before a target is marked as unreachable
hosts:
  default:
    username: urer
    password: pass
metrics:
  system: true
  sensors: true
  power: true
  sel: false       # iDRAC only
  storage: true
  memory: true

running in a container. curl times out. There is no firewall between

**Comment by mrlhansen** [comment]
This is not enough information to go on, but from the sounds of it, this has nothing to do with the exporter itself, but rather your setup.

If there is an actual problem with the exporter I am happy to look into it, but I cannot help with setting it up in your local environment.
