### ISSUE TITLE
Dell iDRAC9 StorageController fails with unmarshall error

### ISSUE THREAD

**Issue by gotmarko** [mrlhansen/idrac_exporter#31]
Working with a Dell iDRAC9 server and I'm hitting this issue

`Error decoding response from url "https://10.11.12.13/redfish/v1/Systems/System.Embedded.1/Storage/AHCI.Slot.3-1": json: cannot unmarshal number 6.0 into Go struct field .StorageControllers.SpeedGbps of type int`

If I change line 187 of model.go to be float64 instead of int, then the data collection works fine.

I did a curl call to that redfish endpoint to get the JSON from there, and it comes back as an int 6 and not a float 6.0 at all.

I'm not sure what the eventual solution will be, but for the systems I'm dealing with, changing the SpeedGbps field from int to float64 is sufficient for my needs, but I do wonder if other folks might hit this same issue.

**Comment by gotmarko** [comment]
[AHCI.Slot.3-1.txt](https://github.com/mrlhansen/idrac_exporter/files/11882976/AHCI.Slot.3-1.txt)

**Comment by mrlhansen** [comment]
Thanks for the report. Your solution is completely fine, so I changed the type to float64.
