### ISSUE TITLE
allow for metric fetch fail-safe mode

### ISSUE THREAD

**Issue by deefdragon** [mrlhansen/idrac_exporter#37]
In the case that some metrics retrievers fail while others pass, the error will still be the only thing displayed.

Instead of failing completely, add an option that fails safely and allows the good metrics to be displayed, even if some/all metrics collectors fail. In this case, the error should only be logged instead of returned.

The opportunity could be taken to wrap the errors [here](https://github.com/mrlhansen/idrac_exporter/blob/master/internal/collector/collector.go#L259C2-L259C2), making it a bit easier to debug in the future what one failed regardless of if this failsafe mode is enabled.

context: I was getting `Error collecting metrics for host HOST: invalid character '<' looking for beginning of value` and had to go through deploying different arrangements of the metrics to figure out what my system supported (it didnt support storage & memory).

**Comment by mrlhansen** [comment]
Hi @deefdragon 

This is also something I have thought about a couple of times, but I could never really decide what the "correct" behavior should be. I am wondering if your suggestion should not just be an option, but simply the default behavior. I think the official node exporter does the same. If some metric fails, the rest will still be returned. One could even think about adding a metric that tells you if the scraping had an error or not.

**Comment by mrlhansen** [comment]
I committed some changes today that should make this the default behavior.
