### ISSUE TITLE
Grafana Agent Integration

### ISSUE THREAD

**Issue by bgatestmg** [mrlhansen/idrac_exporter#40]
Hello, with youre permission i would love to make this available as a native integration for Grafana Agents. 

I am currently working on proxmox native integration and would love to take this on aswell, and since its already written in go should be really easy.

Figured id ask for permission before just doing :)

**Comment by mrlhansen** [comment]
Hi @bgatestmg

Sure, go ahead :) I am just happy that people find the exporter useful.

**Comment by bgatestmg** [comment]
rad! i think it would be an awesome contribution :)
