### ISSUE TITLE
Grafanna  dashboard 

### ISSUE THREAD

**Issue by badharan** [mrlhansen/idrac_exporter#5]
Hey guys !! can you upload grafana dashboards so that we can make use of it

thanks

**Comment by badharan** [comment]
and how to do up the container ?

**Comment by mrlhansen** [comment]
Hey!

I have a fairly complete Grafana dashboard I use myself. I will try to upload it :)

**Comment by mrlhansen** [comment]
Hi @badharan 

I uploaded a JSON export of my dashboard in the `grafana` folder.

To run it via docker, you need to build it first. Clone the repository using Git and then from the root directory of the repository:
```
$ docker build . -t idrac_exporter
```

You then need to create a config file and run it:

```
docker run -v /path/to/config.yml:/config.yml:ro idrac_exporter -config /config.yml
```

**Comment by badharan** [comment]
thanks thanks man !!!

**Comment by badharan** [comment]
badharan@lx-badharan-vm:~$ sudo  docker build . -t idrac_exporter
[sudo] password for badharan:
Sending build context to Docker daemon  511.2MB
Step 1/10 : FROM golang:1.19-alpine3.16 as builder
Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
badharan@lx-badharan-vm:~$




can you upload the docker image in https://quay.io/ so that i can use in docker as well as in podman as well ?
