### ISSUE TITLE
H3C server obtains SKU, power supply and other information

### ISSUE THREAD

**Issue by ilanni2460** [mrlhansen/idrac_exporter#51]
H3C server obtains SKU, power supply and other information

Server model: H3C UniServer R4900 G5

Firmware information: 5.69 V100R001B05D086

No sku,  idrac_power_control_avg_consumed_watts

Get relevant information through redfish:
curl -k https://192.168.70.125/redfish/v1/Systems/1 |jq .

```json
{
  "@odata.context": "/redfish/v1/$metadata#ComputerSystem.ComputerSystem(*)",
  "@odata.id": "/redfish/v1/Systems/1",
  "@odata.type": "#ComputerSystem.v1_5_0.ComputerSystem",
  "Actions": {
    "#ComputerSystem.Reset": {
      "ResetType@Redfish.AllowableValues": [
        "On",
        "ForceOff",
        "ForceRestart",
        "GracefulShutdown",
        "ForcePowerCycle",
        "Nmi"
      ],
      "target": "/redfish/v1/Systems/1/Actions/ComputerSystem.Reset"
    }
  },
  "AssetTag": null,
  "Bios": {
    "@odata.id": "/redfish/v1/Systems/1/Bios"
  },
  "BiosVersion": "5.69 V100R001B05D086",
  "Boot": {
    "BootSourceOverrideEnabled": "Once",
    "BootSourceOverrideEnabled@Redfish.AllowableValues": [
      "Once",
      "Continuous"
    ],
    "BootSourceOverrideMode": "None",
    "BootSourceOverrideMode@Redfish.AllowableValues": [
      "None",
      "Legacy",
      "UEFI"
    ],
    "BootSourceOverrideTarget": "None",
    "BootSourceOverrideTarget@Redfish.AllowableValues": [
      "None",
      "Pxe",
      "Hdd",
      "Cd",
      "BiosSetup"
    ]
  },
  "ChassisPartNumber": "XXXXXX",
  "Description": "System 1",
  "Healthstate": {
    "OverallHealth": "OK",
    "board": "OK",
    "fans": "OK",
    "memory": "OK",
    "pcie": "OK",
    "power": "OK",
    "processor": "OK",
    "storage": "OK",
    "temperature": "OK"
  },
  "HostName": "XXXXXX",
  "Id": "1",
  "IndicatorLED": "Off",
  "Links": {
    "Chassis": [
      {
        "@odata.id": "/redfish/v1/Chassis/1"
      }
    ],
    "ManagedBy": [
      {
        "@odata.id": "/redfish/v1/Managers/1"
      }
    ]
  },
  "LogServices": {
    "@odata.id": "/redfish/v1/Systems/1/LogServices"
  },
  "MaintenanceSerialNumber": "XXXXXX",
  "Manufacturer": "New H3C Technologies Co., Ltd.",
  "Memory": {
    "@odata.id": "/redfish/v1/Systems/1/Memory"
  },
  "MemorySummary": {
    "Count": 4,
    "Status": {
      "Health": "OK",
      "HealthRollup": "OK",
      "State": "Enabled"
    },
    "TotalSystemMemoryGiB": 128
  },
  "Model": "H3C UniServer R4900 G5",
  "Name": "Computer System",
  "NetworkInterfaces": {
    "@odata.id": "/redfish/v1/Systems/1/NetworkInterfaces"
  },
  "Oem": {
    "Public": {
      "BiosVendor": "AMI",
      "IndependentPowerSupply": false,
      "PowerOnStrategy": "RestorePreviousState"
    }
  },
  "PCIeDevices": [
    {
      "@odata.id": "/redfish/v1/Chassis/1/PCIeDevices/1"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/1/PCIeDevices/3"
    }
  ],
  "PCIeFunctions": [
    {
      "@odata.id": "/redfish/v1/Chassis/1/PCIeDevices/1/Functions/1"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/1/PCIeDevices/3/Functions/1"
    }
  ],
  "PartNumber": "XXXX",
  "PowerState": "On",
  "ProcessorSummary": {
    "Count": 1,
    "Model": "Intel(R) Xeon(R) Silver 4314 CPU @ 2.40GHz",
    "Status": {
      "Health": "OK",
      "HealthRollup": "OK",
      "State": "Enabled"
    },
    "TotalCores": 16,
    "TotalThreads": 32
  },
  "Processors": {
    "@odata.id": "/redfish/v1/Systems/1/Processors"
  },
  "SecureBoot": {
    "@odata.id": "/redfish/v1/Systems/1/SecureBoot"
  },
  "SerialNumber": "210235A2RA523BC00697",
  "Status": {
    "Health": "OK",
    "State": "Enabled"
  },
  "Storage": {
    "@odata.id": "/redfish/v1/Systems/1/Storages"
  },
  "SystemType": "Physical",
  "UUID": "77528ec3-1484-04d5-e611-b6cfaaeead2c",
  "Uptime_hours": "1731",
  "kvm": {
    "@odata.id": "/redfish/v1/Systems/1/kvm"
  }
}
```

![1](https://github.com/mrlhansen/idrac_exporter/assets/5058391/ccddda74-6040-4863-87f1-a7f76563ff83)

**Comment by mrlhansen** [comment]
I cannot promise I can get this working, but can you provide the output from the following command?

```
curl -k https://192.168.70.125/redfish/v1/Chassis/1
```

**Comment by ilanni2460** [comment]
@mrlhansen 

curl -k https://192.168.70.125/redfish/v1/Chassis/1

`{
  "@odata.context": "/redfish/v1/$metadata#Chassis.Chassis(SerialNumber,Id,IndicatorLED,PowerState,ChassisType,PartNumber,Description,Thermal,Oem,PCIeDevices,Status,Links,Name,Drives,Power,SKU,NetworkAdapters,LogServices,Manufacturer,AssetTag,Model,IndicatorLED@Redfish.AllowableValues)",
  "@odata.id": "/redfish/v1/Chassis/1",
  "@odata.type": "#Chassis.v1_7_0.Chassis",
  "AssetTag": "",
  "ChassisType": "Rack Mount Chassis",
  "Description": "Computer System Chassis",
  "Drives": {
    "@odata.id": "/redfish/v1/Chassis/1/Drives"
  },
  "Id": "1",
  "IndicatorLED": "Off",
  "IndicatorLED@Redfish.AllowableValues": [
    "Lit",
    "Blinking",
    "Off"
  ],
  "Links": {
    "ComputerSystems": [
      {
        "@odata.id": "/redfish/v1/Systems/1"
      }
    ],
    "ManagedBy": [
      {
        "@odata.id": "/redfish/v1/Managers/1"
      }
    ]
  },
  "LogServices": {
    "@odata.id": "/redfish/v1/Chassis/1/LogServices"
  },
  "Manufacturer": "New H3C Technologies Co., Ltd.",
  "Model": "H3C UniServer R4900 G5",
  "Name": "Computer System Chassis",
  "NetworkAdapters": {
    "@odata.id": "/redfish/v1/Chassis/1/NetworkAdapters"
  },
  "Oem": {
    "Public": {
      "Boards": {
        "@odata.id": "/redfish/v1/Chassis/1/Boards"
      },
      "DeviceMaxNum": {
        "CPUNum": 2,
        "DiskNum": 8,
        "FanNum": 6,
        "MemoryNum": 32,
        "PCIeNum": 4,
        "PowerSupplyNum": 2,
        "StorageCardNum": 4
      },
      "Mainboard": {
        "BoardName": "XXX",
        "SerialNumber": "XXXXXX"
      }
    }
  },
  "PCIeDevices": [
    {
      "@odata.id": "/redfish/v1/Chassis/1/PCIeDevices/1"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/1/PCIeDevices/3"
    }
  ],
  "PartNumber": "XXXX",
  "Power": {
    "@odata.id": "/redfish/v1/Chassis/1/Power"
  },
  "PowerState": "On",
  "SKU": "",
  "SerialNumber": "XXXXXX",
  "Status": {
    "Health": "OK",
    "State": "Enabled"
  },
  "Thermal": {
    "@odata.id": "/redfish/v1/Chassis/1/Thermal"
  }
}
`

**Comment by mrlhansen** [comment]
Thank you. Can you also provide this?

```
curl -k https://192.168.70.125/redfish/v1/Chassis/1/Power
```

**Comment by ilanni2460** [comment]
> Thank you. Can you also provide this?
> 
> ```
> curl -k https://192.168.70.125/redfish/v1/Chassis/1/Power
> ```

{
    "@odata.context":"/redfish/v1/$metadata#Power.Power(PowerControl,Voltages,Id,Name,PowerSupplies)",
    "@odata.id":"/redfish/v1/Chassis/1/Power",
    "@odata.type":"#Power.v1_5_0.Power",
    "Id":"Power",
    "Name":"Power",
    "PowerControl":[
        {
            "@odata.id":"/redfish/v1/Chassis/1/Power#/PowerControl/1",
            "MaxNum":2,
            "MemberId":"1",
            "Name":"System Power Control 1",
            "Oem":{
                "Public":{
                    "CurrentCPUPowerWatts":70,
                    "CurrentDiskPowerWatts":36,
                    "CurrentFanPowerWatts":4,
                    "CurrentMemoryPowerWatts":3
                }
            },
            "PowerConsumedWatts":158,
            "PowerLimit":{
                "CorrectionInMs":30000,
                "LimitException":"NoAction",
                "LimitInWatts":10000,
                "PowerLimitEnable":false
            },
            "PowerMetrics":{
                "MaxConsumedWatts":10000,
                "MinConsumedWatts":150
            },
            "Status":{
                "Health":"OK",
                "State":"Enabled"
            }
        }
    ],
    "PowerSupplies":[
        {
            "@odata.id":"/redfish/v1/Chassis/1/Power#/PowerSupplies/1",
            "FirmwareVersion":"06.02.00",
            "LineInputVoltage":217,
            "LineInputVoltageType":"ACMidLine",
            "Manufacturer":"Great Wall",
            "MemberId":"1",
            "Model":"GW-CRPS550N",
            "Name":"PSU1",
            "Oem":{
                "Public":{
                    "ActiveStandby":"Active",
                    "InputAmperage":0.4,
                    "LineInputCurrent":0.4,
                    "PowerCurrentWatts":82,
                    "PowerID":"1",
                    "PowerOutputWatts":82,
                    "ReadingAmperes":5.34,
                    "SlotNumber":1
                }
            },
            "PowerCapacityWatts":550,
            "PowerSupplyType":"ACorDC",
            "SerialNumber":"210231AE25523BC000TD",
            "Status":{
                "Health":"OK",
                "State":"Enabled"
            }
        },
        {
            "@odata.id":"/redfish/v1/Chassis/1/Power#/PowerSupplies/2",
            "FirmwareVersion":"06.02.00",
            "LineInputVoltage":217,
            "LineInputVoltageType":"ACMidLine",
            "Manufacturer":"Great Wall",
            "MemberId":"2",
            "Model":"GW-CRPS550N",
            "Name":"PSU2",
            "Oem":{
                "Public":{
                    "ActiveStandby":"Active",
                    "InputAmperage":0.372,
                    "LineInputCurrent":0.372,
                    "PowerCurrentWatts":76,
                    "PowerID":"2",
                    "PowerOutputWatts":76,
                    "ReadingAmperes":4.45,
                    "SlotNumber":2
                }
            },
            "PowerCapacityWatts":550,
            "PowerSupplyType":"ACorDC",
            "SerialNumber":"210231AE25523BC000TF",
            "Status":{
                "Health":"OK",
                "State":"Enabled"
            }
        }
    ],
    "Voltages":[
        {
            "LowerThresholdCritical":1.44,
            "LowerThresholdFatal":"N/A",
            "LowerThresholdNonCritical":"N/A",
            "MaxReadingRange":255,
            "MinReadingRange":0,
            "Name":"CPU1_Vcore",
            "ReadingVolts":1.78,
            "SensorNumber":51,
            "Status":{
                "Health":"OK",
                "State":"Enabled"
            },
            "UpperThresholdCritical":2.2,
            "UpperThresholdFatal":"N/A",
            "UpperThresholdNonCritical":"N/A"
        },
        {
            "LowerThresholdCritical":1.08,
            "LowerThresholdFatal":"N/A",
            "LowerThresholdNonCritical":"N/A",
            "MaxReadingRange":255,
            "MinReadingRange":0,
            "Name":"CPU1_DDR_VDDQ1",
            "ReadingVolts":1.22,
            "SensorNumber":52,
            "Status":{
                "Health":"OK",
                "State":"Enabled"
            },
            "UpperThresholdCritical":1.32,
            "UpperThresholdFatal":"N/A",
            "UpperThresholdNonCritical":"N/A"
        },
        {
            "LowerThresholdCritical":1.08,
            "LowerThresholdFatal":"N/A",
            "LowerThresholdNonCritical":"N/A",
            "MaxReadingRange":255,
            "MinReadingRange":0,
            "Name":"CPU1_DDR_VDDQ2",
            "ReadingVolts":1.22,
            "SensorNumber":53,
            "Status":{
                "Health":"OK",
                "State":"Enabled"
            },
            "UpperThresholdCritical":1.32,
            "UpperThresholdFatal":"N/A",
            "UpperThresholdNonCritical":"N/A"
        },
        {
            "LowerThresholdCritical":1.44,
            "LowerThresholdFatal":"N/A",
            "LowerThresholdNonCritical":"N/A",
            "MaxReadingRange":255,
            "MinReadingRange":0,
            "Name":"CPU2_Vcore",
            "ReadingVolts":"N/A",
            "SensorNumber":54,
            "Status":{
                "Health":"OK",
                "State":"Disabled"
            },
            "UpperThresholdCritical":2.2,
            "UpperThresholdFatal":"N/A",
            "UpperThresholdNonCritical":"N/A"
        },
        {
            "LowerThresholdCritical":1.08,
            "LowerThresholdFatal":"N/A",
            "LowerThresholdNonCritical":"N/A",
            "MaxReadingRange":255,
            "MinReadingRange":0,
            "Name":"CPU2_DDR_VDDQ1",
            "ReadingVolts":"N/A",
            "SensorNumber":55,
            "Status":{
                "Health":"OK",
                "State":"Disabled"
            },
            "UpperThresholdCritical":1.32,
            "UpperThresholdFatal":"N/A",
            "UpperThresholdNonCritical":"N/A"
        },
        {
            "LowerThresholdCritical":1.08,
            "LowerThresholdFatal":"N/A",
            "LowerThresholdNonCritical":"N/A",
            "MaxReadingRange":255,
            "MinReadingRange":0,
            "Name":"CPU2_DDR_VDDQ2",
            "ReadingVolts":"N/A",
            "SensorNumber":56,
            "Status":{
                "Health":"OK",
                "State":"Disabled"
            },
            "UpperThresholdCritical":1.32,
            "UpperThresholdFatal":"N/A",
            "UpperThresholdNonCritical":"N/A"
        },
        {
            "LowerThresholdCritical":"N/A",
            "LowerThresholdFatal":"N/A",
            "LowerThresholdNonCritical":"N/A",
            "MaxReadingRange":255,
            "MinReadingRange":0,
            "Name":"PSU1_VOUT",
            "ReadingVolts":12.12,
            "SensorNumber":57,
            "Status":{
                "Health":"OK",
                "State":"Enabled"
            },
            "UpperThresholdCritical":"N/A",
            "UpperThresholdFatal":"N/A",
            "UpperThresholdNonCritical":"N/A"
        },
        {
            "LowerThresholdCritical":"N/A",
            "LowerThresholdFatal":"N/A",
            "LowerThresholdNonCritical":"N/A",
            "MaxReadingRange":255,
            "MinReadingRange":0,
            "Name":"PSU2_VOUT",
            "ReadingVolts":12.12,
            "SensorNumber":60,
            "Status":{
                "Health":"OK",
                "State":"Enabled"
            },
            "UpperThresholdCritical":"N/A",
            "UpperThresholdFatal":"N/A",
            "UpperThresholdNonCritical":"N/A"
        },
        {
            "LowerThresholdCritical":10.8,
            "LowerThresholdFatal":"N/A",
            "LowerThresholdNonCritical":"N/A",
            "MaxReadingRange":255,
            "MinReadingRange":0,
            "Name":"SYS_12V",
            "ReadingVolts":12.24,
            "SensorNumber":63,
            "Status":{
                "Health":"OK",
                "State":"Enabled"
            },
            "UpperThresholdCritical":13.2,
            "UpperThresholdFatal":"N/A",
            "UpperThresholdNonCritical":"N/A"
        },
        {
            "LowerThresholdCritical":4.48,
            "LowerThresholdFatal":"N/A",
            "LowerThresholdNonCritical":"N/A",
            "MaxReadingRange":255,
            "MinReadingRange":0,
            "Name":"SYS_5V",
            "ReadingVolts":4.96,
            "SensorNumber":64,
            "Status":{
                "Health":"OK",
                "State":"Enabled"
            },
            "UpperThresholdCritical":5.52,
            "UpperThresholdFatal":"N/A",
            "UpperThresholdNonCritical":"N/A"
        },
        {
            "LowerThresholdCritical":2.96,
            "LowerThresholdFatal":"N/A",
            "LowerThresholdNonCritical":"N/A",
            "MaxReadingRange":255,
            "MinReadingRange":0,
            "Name":"SYS_3V3",
            "ReadingVolts":3.2,
            "SensorNumber":65,
            "Status":{
                "Health":"OK",
                "State":"Enabled"
            },
            "UpperThresholdCritical":3.6,
            "UpperThresholdFatal":"N/A",
            "UpperThresholdNonCritical":"N/A"
        },
        {
            "LowerThresholdCritical":"N/A",
            "LowerThresholdFatal":"N/A",
            "LowerThresholdNonCritical":"N/A",
            "MaxReadingRange":255,
            "MinReadingRange":0,
            "Name":"PSU1_VIN",
            "ReadingVolts":216,
            "SensorNumber":66,
            "Status":{
                "Health":"OK",
                "State":"Enabled"
            },
            "UpperThresholdCritical":"N/A",
            "UpperThresholdFatal":"N/A",
            "UpperThresholdNonCritical":"N/A"
        },
        {
            "LowerThresholdCritical":"N/A",
            "LowerThresholdFatal":"N/A",
            "LowerThresholdNonCritical":"N/A",
            "MaxReadingRange":255,
            "MinReadingRange":0,
            "Name":"PSU2_VIN",
            "ReadingVolts":216,
            "SensorNumber":69,
            "Status":{
                "Health":"OK",
                "State":"Enabled"
            },
            "UpperThresholdCritical":"N/A",
            "UpperThresholdFatal":"N/A",
            "UpperThresholdNonCritical":"N/A"
        },
        {
            "LowerThresholdCritical":"N/A",
            "LowerThresholdFatal":"N/A",
            "LowerThresholdNonCritical":"N/A",
            "MaxReadingRange":255,
            "MinReadingRange":0,
            "Name":"M_HDD_BP1_12V",
            "ReadingVolts":"N/A",
            "SensorNumber":71,
            "Status":{
                "Health":"OK",
                "State":"Disabled"
            },
            "UpperThresholdCritical":"N/A",
            "UpperThresholdFatal":"N/A",
            "UpperThresholdNonCritical":"N/A"
        },
        {
            "LowerThresholdCritical":"N/A",
            "LowerThresholdFatal":"N/A",
            "LowerThresholdNonCritical":"N/A",
            "MaxReadingRange":255,
            "MinReadingRange":0,
            "Name":"R_HDD_BP1_12V",
            "ReadingVolts":"N/A",
            "SensorNumber":82,
            "Status":{
                "Health":"OK",
                "State":"Disabled"
            },
            "UpperThresholdCritical":"N/A",
            "UpperThresholdFatal":"N/A",
            "UpperThresholdNonCritical":"N/A"
        },
        {
            "LowerThresholdCritical":"N/A",
            "LowerThresholdFatal":"N/A",
            "LowerThresholdNonCritical":"N/A",
            "MaxReadingRange":255,
            "MinReadingRange":0,
            "Name":"R_HDD_BP2_12V",
            "ReadingVolts":"N/A",
            "SensorNumber":83,
            "Status":{
                "Health":"OK",
                "State":"Disabled"
            },
            "UpperThresholdCritical":"N/A",
            "UpperThresholdFatal":"N/A",
            "UpperThresholdNonCritical":"N/A"
        },
        {
            "LowerThresholdCritical":"N/A",
            "LowerThresholdFatal":"N/A",
            "LowerThresholdNonCritical":"N/A",
            "MaxReadingRange":255,
            "MinReadingRange":0,
            "Name":"M_HDD_BP2_12V",
            "ReadingVolts":"N/A",
            "SensorNumber":84,
            "Status":{
                "Health":"OK",
                "State":"Disabled"
            },
            "UpperThresholdCritical":"N/A",
            "UpperThresholdFatal":"N/A",
            "UpperThresholdNonCritical":"N/A"
        },
        {
            "LowerThresholdCritical":2.34,
            "LowerThresholdFatal":"N/A",
            "LowerThresholdNonCritical":"N/A",
            "MaxReadingRange":255,
            "MinReadingRange":0,
            "Name":"CPU1_DDR_VPP1",
            "ReadingVolts":2.56,
            "SensorNumber":128,
            "Status":{
                "Health":"OK",
                "State":"Enabled"
            },
            "UpperThresholdCritical":2.76,
            "UpperThresholdFatal":"N/A",
            "UpperThresholdNonCritical":"N/A"
        },
        {
            "LowerThresholdCritical":2.34,
            "LowerThresholdFatal":"N/A",
            "LowerThresholdNonCritical":"N/A",
            "MaxReadingRange":255,
            "MinReadingRange":0,
            "Name":"CPU1_DDR_VPP2",
            "ReadingVolts":2.56,
            "SensorNumber":129,
            "Status":{
                "Health":"OK",
                "State":"Enabled"
            },
            "UpperThresholdCritical":2.76,
            "UpperThresholdFatal":"N/A",
            "UpperThresholdNonCritical":"N/A"
        },
        {
            "LowerThresholdCritical":2.34,
            "LowerThresholdFatal":"N/A",
            "LowerThresholdNonCritical":"N/A",
            "MaxReadingRange":255,
            "MinReadingRange":0,
            "Name":"CPU2_DDR_VPP1",
            "ReadingVolts":"N/A",
            "SensorNumber":130,
            "Status":{
                "Health":"OK",
                "State":"Disabled"
            },
            "UpperThresholdCritical":2.76,
            "UpperThresholdFatal":"N/A",
            "UpperThresholdNonCritical":"N/A"
        },
        {
            "LowerThresholdCritical":2.34,
            "LowerThresholdFatal":"N/A",
            "LowerThresholdNonCritical":"N/A",
            "MaxReadingRange":255,
            "MinReadingRange":0,
            "Name":"CPU2_DDR_VPP2",
            "ReadingVolts":"N/A",
            "SensorNumber":131,
            "Status":{
                "Health":"OK",
                "State":"Disabled"
            },
            "UpperThresholdCritical":2.76,
            "UpperThresholdFatal":"N/A",
            "UpperThresholdNonCritical":"N/A"
        },
        {
            "LowerThresholdCritical":"N/A",
            "LowerThresholdFatal":"N/A",
            "LowerThresholdNonCritical":"N/A",
            "MaxReadingRange":255,
            "MinReadingRange":0,
            "Name":"HDD_BP1_12V",
            "ReadingVolts":12.16,
            "SensorNumber":132,
            "Status":{
                "Health":"OK",
                "State":"Enabled"
            },
            "UpperThresholdCritical":"N/A",
            "UpperThresholdFatal":"N/A",
            "UpperThresholdNonCritical":"N/A"
        },
        {
            "LowerThresholdCritical":"N/A",
            "LowerThresholdFatal":"N/A",
            "LowerThresholdNonCritical":"N/A",
            "MaxReadingRange":255,
            "MinReadingRange":0,
            "Name":"HDD_BP2_12V",
            "ReadingVolts":"N/A",
            "SensorNumber":133,
            "Status":{
                "Health":"OK",
                "State":"Disabled"
            },
            "UpperThresholdCritical":"N/A",
            "UpperThresholdFatal":"N/A",
            "UpperThresholdNonCritical":"N/A"
        },
        {
            "LowerThresholdCritical":"N/A",
            "LowerThresholdFatal":"N/A",
            "LowerThresholdNonCritical":"N/A",
            "MaxReadingRange":255,
            "MinReadingRange":0,
            "Name":"HDD_BP3_12V",
            "ReadingVolts":"N/A",
            "SensorNumber":134,
            "Status":{
                "Health":"OK",
                "State":"Disabled"
            },
            "UpperThresholdCritical":"N/A",
            "UpperThresholdFatal":"N/A",
            "UpperThresholdNonCritical":"N/A"
        },
        {
            "LowerThresholdCritical":2,
            "LowerThresholdFatal":"N/A",
            "LowerThresholdNonCritical":"N/A",
            "MaxReadingRange":255,
            "MinReadingRange":0,
            "Name":"SYS_3V_BAT",
            "ReadingVolts":3.28,
            "SensorNumber":235,
            "Status":{
                "Health":"OK",
                "State":"Enabled"
            },
            "UpperThresholdCritical":3.68,
            "UpperThresholdFatal":"N/A",
            "UpperThresholdNonCritical":"N/A"
        }
    ]
}

**Comment by ilanni2460** [comment]
@mrlhansen 
Use idrac_exporter to debug the H3C server logs as follows:
```
2024-02-21T10:03:32.830 DEBUG Querying url "https://192.168.70.125/redfish/v1/Chassis/1/Power"
2024-02-21T10:03:35.064 DEBUG Error decoding response from url "https://192.168.70.125/redfish/v1/Chassis/1/Power": json: cannot unmarshal string into Go struct field .Voltages.LowerThresholdFatal of type float64
```
