### ISSUE TITLE
Can we have a container 

### ISSUE THREAD

**Issue by badharan** [mrlhansen/idrac_exporter#6]
so can yo publish the container in docker.io or quay.io

**Comment by badharan** [comment]
any update over this ? there are some internal calls thats blocked in our env , so creating docker fails , so can you please udpate the image in any artidactory like quay , dockeri.io , so we can easily pull that

**Comment by mrlhansen** [comment]
I have been away from this project for a while for personal reasons, I will see what I can do :)

**Comment by badharan** [comment]
thanks dude lemme try and will let you know
