### ISSUE TITLE
help

### ISSUE THREAD

**Issue by onlineyh** [mrlhansen/idrac_exporter#64]
The server I need to monitor is ThinkSystem SR658, and I have noticed an issue. May I ask if it sometimes displays and sometimes it doesn't? What is the reason for this?

![image](https://github.com/mrlhansen/idrac_exporter/assets/41468337/6d92d149-c4cb-4e46-92cc-c7695c99b068)
![image](https://github.com/mrlhansen/idrac_exporter/assets/41468337/6812d79d-4238-44c6-96d9-4b721170e54f)

**Comment by onlineyh** [comment]
According to your prompt, refer to my previous configuration of SNMP. After adding the following image, it will be normal. thanks
![企业微信截图_17135190055666](https://github.com/mrlhansen/idrac_exporter/assets/41468337/b93f2dd3-14da-4f6c-b3d0-22446d335172)

**Comment by onlineyh** [comment]
May I ask again if the issue shown in the picture below is caused by the absence of system activity events on my server
![image](https://github.com/mrlhansen/idrac_exporter/assets/41468337/d8dc3e8b-d548-4201-86ab-84a753402b79)
![image](https://github.com/mrlhansen/idrac_exporter/assets/41468337/e215cdb1-9be2-4ca2-9c59-47b0a01a73b7)

**Comment by mrlhansen** [comment]
Yes, I believe that page is blank unless there is an active warning or error on the system.

**Comment by onlineyh** [comment]
Thank you very much！
