### ISSUE TITLE
Request idrac_exporter to add metrics for capturing CPU models

### ISSUE THREAD

**Issue by ilanni2460** [mrlhansen/idrac_exporter#66]
Request idrac_exporter to add metrics for capturing CPU models.
Currently, idrac_exporter can capture the number of CPUs.

**Comment by mrlhansen** [comment]
Hi @ilanni2460 

The metric for the CPU count also contains the model (if available).

```
idrac_system_cpu_count{model="AMD EPYC 7742 64-Core Processor"} 2
```
