### ISSUE TITLE
Gathering iDRAC8 data using the Redfish API takes a long time

### ISSUE THREAD

**Issue by Fengqiv** [mrlhansen/idrac_exporter#68]
![image](https://github.com/mrlhansen/idrac_exporter/assets/96766709/9a4212ee-9a61-4de6-9d67-69d7a9bbf415)

**Comment by mrlhansen** [comment]
Hi @Fengqiv

If you have all metrics groups enabled, then yes, it can be quite slow to pull all information. Unfortunately there is nothing I can do about that. Sometimes it helps to restart iDRAC itself.

The only way to "solve" this would be to pull the information from iDRAC asynchronously in the exporter - which is something I have been considering as an option - but that is currently not possible.

**Comment by mrlhansen** [comment]
Maybe the Web UI is collecting information in parallel, which the exporter doesn't do. Pulling information in parallel in the exporter could probably be useful, I will try to look into this when I have some time.

**Comment by Fengqiv** [comment]
![image](https://github.com/mrlhansen/idrac_exporter/assets/96766709/4488ff44-2910-4aae-a779-1a04e90623ad)
Collecting information in parallel can shorten the time required. Different iDRAC hardware performance may also lead to varying collection times.
