### ISSUE TITLE
Can / return 200?

### ISSUE THREAD

**Issue by 7840vz** [mrlhansen/idrac_exporter#7]
Thanks for great exporter.
I deployed idrac_exporter in kubernetes, and would like to use liveness probe to check that idrac_exporter is alive.  Is it possible to make "/" or "/metrics" to return 200 HTTP code instead of 404 not found so it is possible to setup such health check?

**Comment by mrlhansen** [comment]
It might be better to add a `/health` endpoint that simply returns 200 for now, and potentially more useful information in the future. I can definitely add that.
