### ISSUE TITLE
How does Grafana's Dashboard display CPU details?

### ISSUE THREAD

**Issue by ilanni2460** [mrlhansen/idrac_exporter#76]
Hi,
Now that I have obtained the CPU metrics through idrac_exporter, I want to display the CPU details on the Dashboard. I don’t know how to configure this. Please give me some advice.

In fact, it is to display the model content of the idrac_system_cpu_count metric.
![1](https://github.com/mrlhansen/idrac_exporter/assets/5058391/9cb2a2f3-85e6-414a-9085-0a1f43118bb5)

**Comment by mrlhansen** [comment]
Hi @ilanni2460 

Use the panel called "Stats" (at least in the English version). As part of the query, under Legend use `{{model}}` as shown on the attached screenshot.

![image](https://github.com/mrlhansen/idrac_exporter/assets/31279460/181ec454-b382-449a-858f-f5681665a1c0)

**Comment by ilanni2460** [comment]
@mrlhansen 

Thank you very much for your reply. After I followed what you said, I found that it didn't work. Look at the picture below:
![1](https://github.com/mrlhansen/idrac_exporter/assets/5058391/b783dc2d-258e-46d4-89e8-426ab1e15563)

**Comment by mrlhansen** [comment]
Unfortunately, I am not really sure why it does not work. This is how it should be done.

**Comment by mrlhansen** [comment]
I think I have the solution now. In the panel on the right hand side, under "Text mode" use "Name".
![image](https://github.com/mrlhansen/idrac_exporter/assets/31279460/ab03bff4-55b8-4971-a892-97d8e4f3ba8d)

**Comment by ilanni2460** [comment]
> I think I have the solution now. In the panel on the right hand side, under "Text mode" use "Name". ![image](https://private-user-images.githubusercontent.com/31279460/333808140-ab03bff4-55b8-4971-a892-97d8e4f3ba8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2ODQyOTYsIm5iZiI6MTcxNjY4Mzk5NiwicGF0aCI6Ii8zMTI3OTQ2MC8zMzM4MDgxNDAtYWIwM2JmZjQtNTViOC00OTcxLWE4OTItOTdkOGU0ZjNiYThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDAwMzk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiYWViMjZjZThhNGUyNjQ5MmZhNTcxMDRlNjRlNzkzYjNhNWRiODU4NjMwYjc0NGU1ODQ3NGQzMzVmM2JjOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.82pmJniJoYSUFRIVfzBirzY6-ymOFss6mkcTWHOTzQM)

Wow, you are so handsome. This can indeed be displayed. Thank you so much! ! !

![1](https://github.com/mrlhansen/idrac_exporter/assets/5058391/cd3087a9-f48d-4dd8-ad8e-aa9fb56c8381)
