### ISSUE TITLE
SEL Query issues 

### ISSUE THREAD

**Issue by bgatestmg** [mrlhansen/idrac_exporter#78]
Having issues with the query for the SEL

the query you provide is: 
```
idrac_sel_entry{job=~"$job", instance=~"$instance"} * 1000 < ${__to} and 
idrac_sel_entry{job=~"$job", instance=~"$instance"} * 1000 > ${__from}
```

This gives a no data even though my dashbaord range is set to the last 6 hours and we had an event.

if i use this query: `idrac_sel_entry{job=~"$job", instance=~"$instance"} * 1000 `it shows me the SEL for all time, but not in my dashboards range

**Comment by mrlhansen** [comment]
Hi @bgatestmg 

If you increase the interval, will the event eventually be shown? I am wondering if there could be an issue with timezone.

**Comment by bgatestmg** [comment]
It would not sadly, I increased it all the way to 7 days with no luck

From: Martin Hansen ***@***.***>
Date: Wednesday, May 22, 2024 at 2:14 AM
To: mrlhansen/idrac_exporter ***@***.***>
Cc: Brian Gates ***@***.***>, Mention ***@***.***>
Subject: Re: [mrlhansen/idrac_exporter] SEL Query issues (Issue #78)

Hi @bgatestmg<https://github.com/bgatestmg>

If you increase the interval, will the event eventually be shown? I am wondering if there could be an issue with timezone.

**Comment by mrlhansen** [comment]
The only thing I can think of is the clock in iDRAC being wrong. You can try to take the value from one of the `idrac_sel_entry` entries and convert it from Unix timestamp and check that the time looks correct. You can use e.g. https://www.unixtimestamp.com/ to do the conversion.

**Comment by mrlhansen** [comment]
There is also the possibility that the time format from iDRAC is somehow different for your systems and the program is doing the conversion to Unix timestamp incorrectly. In any case, I would check the the value for the `idrac_sel_entry` entries to see if they are sensible.
