### ISSUE TITLE
Inventory metrics return NaN

### ISSUE THREAD

**Issue by 7840vz** [mrlhansen/idrac_exporter#8]
Currently metadata metrics return NaN as value:

```
idrac_bios_version{version="2.11.2"} NaN
idrac_machine{manufacturer="Dell Inc.",model="PowerEdge R740",serial="xxxxx",sku="xxxx"} NaN
```

But as a common practice, value for such metrics should be always '1' 
+ suffix _info could be also great (if you are still ok with breaking metric names)

https://prometheus.io/docs/practices/naming/
https://www.robustperception.io/exposing-the-software-version-to-prometheus/

**Comment by mrlhansen** [comment]
I am not sure I understand your `_info` comment. Would you rename the two metrics mentioned here to include `_info` at the end?

**Comment by mrlhansen** [comment]
I think it's fine to fix it. I will rename them to `idrac_bios_info` (having version in the name is redundant) and `idrac_machine_info`.
