### ISSUE TITLE
Prometheus.yml   not same with  idrac.yml  target will get erro ,

### ISSUE THREAD

**Issue by tqangxl** [mrlhansen/idrac_exporter#83]
The issue reproduces：
Prometheus.yml :
 "targets": [
            "192.168.1.102"
        ]
-------------------------
 idrac.yml :
 （target:）
hosts:
  192.168.1.106:
    username: "USERID"
    password: "   "
will get erro ：
----------------------------------

 
when  idrac.yml target same with Prometheus.yml  will be ok
----------
pls check    idrac.yml   target**s**  same with   Prometheus.yml

2024/06/21 09:09:58 http: panic serving 127.0.0.1:15917: runtime error: invalid memory address or nil pointer dereference
goroutine 56 [running]:
net/http.(*conn).serve.func1()
        D:/Program Files/Go/src/net/http/server.go:1898 +0xbe
panic({0x13c60c0?, 0x175b0b0?})
        D:/Program Files/Go/src/runtime/panic.go:770 +0x132
github.com/mrlhansen/idrac_exporter/internal/config.(*RootConfig).GetHostCfg(0x177a5e0, {0xc0003c0014, 0xd})
        C:/Users/James/go/pkg/mod/github.com/mrlhansen/idrac_exporter@v1.3.0/internal/config/config.go:23 +0x10f
github.com/mrlhansen/idrac_exporter/internal/collector.GetCollector({0xc0003c0014, 0xd})
        C:/Users/James/go/pkg/mod/github.com/mrlhansen/idrac_exporter@v1.3.0/internal/collector/collector.go:477 +0x1b4
main.MetricsHandler({0x14e8480, 0xc0001e22a0}, 0xc0001b25a0)
        C:/Users/James/go/pkg/mod/github.com/mrlhansen/idrac_exporter@v1.3.0/cmd/idrac_exporter/handler.go:54 +0x1ce
net/http.HandlerFunc.ServeHTTP(0x177abd0?, {0x14e8480?, 0xc0001e22a0?}, 0x1242dda?)
        D:/Program Files/Go/src/net/http/server.go:2166 +0x29
net/http.(*ServeMux).ServeHTTP(0x10570b9?, {0x14e8480, 0xc0001e22a0}, 0xc0001b25a0)
        D:/Program Files/Go/src/net/http/server.go:2683 +0x1ad
net/http.serverHandler.ServeHTTP({0xc000198cc0?}, {0x14e8480?, 0xc0001e22a0?}, 0x6?)
        D:/Program Files/Go/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc0003023f0, {0x14e8c78, 0xc000198660})
        D:/Program Files/Go/src/net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 1
        D:/Program Files/Go/src/net/http/server.go:3285 +0x4b4

**Comment by mrlhansen** [comment]
The above error has been fixed in v1.3.1 that I released yesterday.

You have to ensure that the `idrac.yml` has the information necessary for the targets in Prometheus, this information cannot be retrieved automatically. For the `idrac_exporter` you can also use the `default` section under `hosts` if all targets have the same username password.

**Comment by tqangxl** [comment]
nice work !
thanks!
