### ISSUE TITLE
add  lenovo resource OK？

### ISSUE THREAD

**Issue by tqangxl** [mrlhansen/idrac_exporter#84]
ref：
https://pubs.lenovo.com/tsm/tsm_rest_api_introduction_ic
 https://github.com/lenovo/python-redfish-lenovo/tree/master
https://github.com/lenovo/powershell-redfish-lenovo

https://pubs.lenovo.com/tsm/get_log_service_instance

thanks!

**Comment by mrlhansen** [comment]
Lenovo machines are supported by the exporter (I use it for Lenovo machines myself).

Are you specifically asking about the event logs? I know those are not working with Lenovo.

**Comment by tqangxl** [comment]
![image](https://github.com/mrlhansen/idrac_exporter/assets/9669944/5814dc25-fc4b-4790-9fd9-5e653f3cd246)

If there are components with warnings or errors displayed, can the specific component causing the warning or error be shown on Dashboard?

**Comment by tqangxl** [comment]
and add  this is ok ？
![image](https://github.com/mrlhansen/idrac_exporter/assets/9669944/8bfdac1f-da9d-4718-9bcc-334202d0ecb7)

**Comment by mrlhansen** [comment]
* I am surprised if the global health status does not say "Warning" if any of the components show a warning. Is that really the case? 
* Power utilization is already implemented but it has to be enabled in the configuration. Did you set `power: true` under `metrics` in the configuration?
* I am not sure show reliable system utilization is from the BMC. I would really suggest to collect this from the operating system.

**Comment by tqangxl** [comment]
ok.thanks your replay!
