### ISSUE TITLE
slowe

### ISSUE THREAD

**Issue by tqangxl** [mrlhansen/idrac_exporter#85]
0	cannot perform request to "http://127.0.0.1:9348/metrics?target=192.168.12.149": Get "http://127.0.0.1:9348/metrics?target=192.168.12.149": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
![image](https://github.com/mrlhansen/idrac_exporter/assets/9669944/dd82c1ec-87dd-4295-8d2e-3fd69aa0ea32)

**Comment by mrlhansen** [comment]
Hi @tqangxl 

Yes, it can be slow (which I also write in the README file). You need to increase the scrape timeout in Prometheus. I cannot do anything about it - it's the BMC on the nodes that are slow in responding.
