### ISSUE TITLE
How to use idrac_exporter-v1.4.1-linux-amd64？

### ISSUE THREAD

**Issue by love6875520** [mrlhansen/idrac_exporter#91]
I have rename the file to  idrac_exporter-v1.4.1-linux-amd64.tar

but it tell me "tar: This does not look like a tar archive"

**Comment by mrlhansen** [comment]
The file is the binary itself and not an archive. However, you might need to manually set the executable bit on the file.

```
$ chmod +x idrac_exporter-v1.4.1-linux-amd64
$ ./idrac_exporter-v1.4.1-linux-amd64
```

**Comment by love6875520** [comment]
It works,thx!
