### ISSUE TITLE
CPU Utilization metrics missing 

### ISSUE THREAD

**Issue by Rohith-Scalers** [mrlhansen/idrac_exporter#93]
Is there a way to retrieve CPU utilization metrics from iDRAC? This metric appears to be missing from the exporter. I have also tried using the [Redfish API](https://developer.dell.com/apis/2978/versions/7.xx/openapi.yaml/paths/~1redfish~1v1~1Systems~1%7BComputerSystemId%7D~1Processors~1%7BProcessorId%7D~1ProcessorMetrics/get), but it does not seem to be available there either. If there's another method to access these metrics, please let me know. Thank you!

**Comment by mrlhansen** [comment]
Hi @Rohith-Scalers 

I have not checked thoroughly, but I do not believe this is part of the Redfish specification. I think there are some non-standard vendor specific implementations. However, I would argue that this kind of information should be scraped from the operating system, e.g. using the [node exporter](https://github.com/prometheus/node_exporter), which in any case will contain more reliable information.

**Comment by Rohith-Scalers** [comment]
Thank you @mrlhansen
