### ISSUE TITLE
About resource usage

### ISSUE THREAD

**Issue by love6875520** [mrlhansen/idrac_exporter#96]
I have collect nearly 500 machines,when i enable events and network metrics,nearly 30 machines collect stat is PENDING,when i disable events and network metrics,PENDING machine is less than 10

So i want to ask for how to adjust machine resource which run idrac_exporter to reduce the PENDING machine quantity？

More CPU cores or high CPU frequency requirements?

**Comment by mrlhansen** [comment]
Hi @love6875520 

I am not sure I fully understand. Where do you see the PENDING state? In Prometheus? Maybe you can send me a screenshot.

In general scraping all metrics can be very slow, so you need to make sure you allow for enough time for the scrape to finish and have a large enough interval between scrapes. If scraping takes 50s and you scrape every 30s then I am not sure what happens to be honest.

**Comment by love6875520** [comment]
Yes,it is in Prometheus
and my config.yml is:
address: 0.0.0.0 
port: 9348 
timeout: 10
retries: 3

so,maybe i need to augment the “timeout”

**Comment by mrlhansen** [comment]
I am sorry, but I still do not understand.

Do you see the PENDING state under "Targets" or under "Alerts"?

**Comment by love6875520** [comment]
![Uploading screenshot-20240829-095008.jpg…]()

**Comment by love6875520** [comment]
how to upload screenshot img，or how to send the image to you？

**Comment by love6875520** [comment]
1、scrape_interval: 60s
2、
name: iDrac timeout
expr: up{job=~".*idrac-monitor.*"} == 0
for: 5m

**Comment by mrlhansen** [comment]
* How long is your `scrape_timeout` in Prometheus? Make sure the scrapes do not time out.
* Does the scrape take longer than 60s when you enable events and network metrics? If it does, then you need to increase the `scrape_interval` to maybe 2m instead.

**Comment by love6875520** [comment]
The scrape_timeout is set to the global default (10s)

Thank you for your support，I'll adjust the config and watch for some days

**Comment by love6875520** [comment]
I have disabled the network metrics，The PENDING machine is less than 10，thank you for your help again！
