### ISSUE TITLE
add new Status Dashboard

### ISSUE THREAD

**Issue by tqangxl** [mrlhansen/idrac_exporter#97]
Could you add the parts that are not currently included in our existing icons, such as the "Overall Machine Status Dashboard" in the image below? I want to transfer all of them to our project
from:
https://github.com/ilovepancakes95/idrac_snmp-grafana
I don't want to use Telegraf and InfluxDB.
Telegraf for data collection with SNMP Input Plugin
InfluxDB for time series and table data storage

**use victoriametrics  and  victorialogs?**
![image](https://github.com/user-attachments/assets/5726bed8-ce61-4458-989b-f6d22e6c41e4)

**Comment by mrlhansen** [comment]
Hi @tqangxl 

Which things are you missing specifically? The following status metrics are already exported.

* System health (global): `idrac_system_health`
* FAN health: `idrac_sensors_fan_health`
* Power supply health: `idrac_power_supply_health`
* Storage health: `idrac_drive_health`
* Memory health: `idrac_memory_module_health`
* Network interface health: `idrac_network_interface_health`

Or do you simply want these added to the dashboard for the idrac exporter?

**Comment by tqangxl** [comment]
The main idea is to provide a visual for clients who are not technically savvy, so that they can look at the image and immediately understand whether there are any hardware issues with the main components of the host machine.

**Comment by tqangxl** [comment]
nice work!!!!!
good job!!!
thanks!!!

Martin Hansen ***@***.***> 于2024年10月23日周三 18:43写道：

**Comment by mrlhansen** [comment]
Great! I added the new dashboard to the repo and fixed a couple of errors: https://github.com/mrlhansen/idrac_exporter/blob/master/grafana/status-alternative.json
