### ISSUE TITLE
HP server hard drive and network cannot be displayed and cannot be accessed anywhere

### ISSUE THREAD

**Issue by dl1021** [mrlhansen/idrac_exporter#99]
![image](https://github.com/user-attachments/assets/bdf82378-1461-4077-b384-cf7b3c1e14f1)
HP server hard drive and network cannot be displayed and cannot be accessed anywhere。

**Comment by mrlhansen** [comment]
Hi @dl1021 

I will try to have a look. In the mean time, could you run the exporter with the `-verbose` flag and send me the log output when you try to scrape the machine?

**Comment by mrlhansen** [comment]
For the network part. I checked some Gen9 and Gen10 machines, and information about the network is simply not available via the Redfish API. On Gen11 machines the information is correctly reported.

For the storage part. This is working on all my machines, so I need some debug information from you, starting with the information requested in the previous comment.

**Comment by dl1021** [comment]
Sorry for how to reply to your email late. There has been no time to deal with other issues recently to deal with this problem. When there is time in the future, I will provide you with the information you need here. Thank you for your reply




---Original---
From: "Martin ***@***.***&gt;
Date: Thu, Sep 26, 2024 16:51 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [mrlhansen/idrac_exporter] HP server hard drive and networkcannot be displayed and cannot be accessed anywhere (Issue #99)




 
For the network part. I checked some Gen9 and Gen10 machines, and information about the network is simply not available via the Redfish API. On Gen11 machines the information is correctly reported.
 
For the storage part. This is working on all my machines, so I need some debug information from you, starting with the information requested in the previous comment.
